trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  jobs:
  - job: 'Build'
    steps:
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'ambs1'
        Phase: 'STARTED'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'ambs1'
        Phase: 'COMPLETED'
  - job: 'Test'
    dependsOn: "Build"
    steps:
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'ambs1'
        upstream: 'Build'
        Phase: 'STARTED'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'ambs1'
        upstream: 'Build'
        Phase: 'COMPLETED'
 


  
- stage: Test
  jobs:
  - job: "Deploy"
    steps:
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'ambs1'
        upstream: 'Test'
        Phase: 'STARTED'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here.
          
          echo 'Hello world '
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'ambs1'
        upstream: 'Test'
        Phase: 'COMPLETED'
    

  - job: "Prod"
    pool: server
    dependsOn: "Deploy"
    steps:
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'ambs1'
        UpstreamJob: 'Deploy'
        Phase: 'STARTED'
    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: 'ambs1'
        UpstreamJob: 'cdfcsdd'
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'ambs1'
        UpstreamJob: 'Deploy'
        Phase: 'COMPLETED'
        

  
  




  



  