trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  jobs:
  - job: 'Build'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
  - job: 'Test'
    dependsOn: "Build"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
 


  
- stage: Test
  jobs:
  - job: "Deploy"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here.
          
          echo 'Hello world '

  - job: "Prod"
    pool: server
    dependsOn: "Deploy"
    steps:
    - task: ServiceNow-DevOps-Server-Artifact-Registration@1
      inputs:
        connectedServiceName: 'ambs1'
        artifactRegistrationPayload: |
          {
             "artifacts": [
                {
                   "name": "<artifact name>",
                   "version": "1.$(build.buildId)",
                   "semanticVersion": "1.$(build.buildId).0",
                   "repositoryName": "<artifact repository name>"
                },
                {
                   "name": "<artifact name>",
                   "version": "1.$(build.buildId)",
                   "semanticVersion": "1.$(build.buildId).0",
                   "repositoryName": "<artifact repository name>"
                }
             ],
             "pipelineName": "$(system.teamProject)/$(build.definitionName)",
             "taskExecutionNumber": "$(build.buildId)",
             "stageName": "$(system.jobDisplayName)",
             "branchName": "$(build.sourceBranchName)"
          }
    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: 'ambs1'
        UpstreamJob: 'kjdjhagsydu'

    - task: Delay@1
      inputs:
        delayForMinutes: '0'
        

  
  




  



  
