trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  jobs:
  - job: 'Build'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
  - job: 'Test'
    dependsOn: "Build"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
  - job: 'NonBlocking'
    pool: server
    dependsOn: "Test"
    steps:
      - task: InvokeRESTAPI@1
        inputs:
          connectionType: 'connectedServiceName'
          serviceConnection: 'Mohan Azure'
          method: 'POST'
          body: |
            {
                       "buildNumber": "$(build.buildId)",
                       "isMultiBranch": "true",
                       "branchName": "$(build.sourceBranchName)"
                      }
          waitForCompletion: 'true'
 


  
- stage: Test
  jobs:
  - job: "Deploy"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here.
          
          echo 'Hello world '

  - job: "Prod"
    pool: server
    dependsOn: "Deploy"
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'Mohan Azure'
        method: 'POST'
        body: |
            {
                       "buildNumber": "$(build.buildId)",
                       "isMultiBranch": "true",
                       "branchName": "$(build.sourceBranchName)"
                      }
        waitForCompletion: 'true'

    - task: Delay@1
      inputs:
        delayForMinutes: '0'
        

  
  




  



  
