trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
jobs:

- job: 'Build'
  steps:
  - task: ServiceNow Job Notification@0
    inputs:
      connectedServiceName: 'AzureDevOpsPoc'
      Phase: 'STARTED'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world'

  - task: ServiceNow Job Notification@0
    inputs:
      connectedServiceName: 'Mohan Connection'
      Phase: 'COMPLETED'


- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
    maxParallel: 2
  steps:

  - task: ServiceNow Job Notification@0
    inputs:
      connectedServiceName: 'AzureDevOpsPoc'
      upstream: 'Build'
      Phase: 'STARTED'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      pip install -r django-basic/requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest-django
      cd django-basic/azuredemo
      pytest --junitxml=../../reports/django-basic.xml
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'reports/django-basic.xml'
      testRunTitle: '$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)] - Python $(python.version)'
    condition: succeededOrFailed()
  
  - task: ServiceNow Job Notification@0
    inputs:
      connectedServiceName: 'AzureDevOpsPoc'
      upstream: 'Build'
      Phase: 'COMPLETED'

- job: "Deploy"
  steps:
  
  - task: ServiceNow Job Notification@0
    inputs:
      connectedServiceName: 'AzureDevOpsPoc'
      upstream: 'Test'
      Phase: 'STARTED'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world'

  - task: ServiceNow Job Notification@0
    inputs:
      connectedServiceName: 'AzureDevOpsPoc'
      upstream: 'Test'
      Phase: 'COMPLETED'



  



  
