trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
jobs:

- job: 'Build'
  steps:
  - task: ServiceNow Job Notification@0
    inputs:
      connectedServiceName: 'MohanPoc Connection'
      Phase: 'STARTED'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world '

  - task: ServiceNow Job Notification@0
    inputs:
      connectedServiceName: 'MohanPoc Connection'
      Phase: 'COMPLETED'


- job: 'Test'
  dependsOn: 'Build'
  steps:
  - task: ServiceNow Job Notification@0
    inputs:
      connectedServiceName: 'MohanPoc Connection'
      upstream: 'Build'
      Phase: 'STARTED'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      pip install -r django-basic/requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest-django
      cd django-basic/azuredemo
      pytest --junitxml=../../reports/django-basic.xml
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'reports/django-basic.xml'
      testRunTitle: '$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)] - Python $(python.version)'
    condition: succeededOrFailed()
  
  - task: ServiceNow Job Notification@0
    inputs:
      connectedServiceName: 'MohanPoc Connection'
      upstream: 'Build'
      Phase: 'COMPLETED'

- job: "Deploy"
  dependsOn: 'Test'
  steps:
  - task: ServiceNow Job Notification@0
    inputs:
      connectedServiceName: 'MohanPoc Connection'
      upstream: 'Test'
      Phase: 'STARTED'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world'

  - task: ServiceNow Job Notification@0
    inputs:
      connectedServiceName: 'MohanPoc Connection'
      upstream: 'Test'
      Phase: 'COMPLETED'

- job: "Prod"
  pool: server
  dependsOn: "Deploy"
  steps:

  - task: Service Now Job Notification Server Extension@1
    inputs:
      connectedServiceName: 'MohanPoc Connection'
      UpstreamJob: 'Deploy'
      Phase: 'STARTED'

  - task: Delay@1
    inputs:
      delayForMinutes: '0'

  - task: Service Now Job Notification Server Extension@1
    inputs:
      connectedServiceName: 'MohanPoc Connection'
      UpstreamJob: 'Deploy'
      Phase: 'COMPLETED'
  




  



  
