trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  jobs:
  - job: 'Build'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
  - job: 'Test'
    dependsOn: "Build"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
    - script: |
        python -m pip install --upgrade pip
        pip install -r django-basic/requirements.txt
      displayName: 'Install dependencies'
    - script: |
        pip install pytest-django
        cd django-basic/azuredemo
        pytest --junitxml=../../reports/django-basic.xml
      displayName: 'Run tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'reports/django-basic.xml'
        testRunTitle: '$(Agent.JobName)'
      condition: succeededOrFailed()
 


  
- stage: Test
  jobs:
  - job: "Deploy"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here.
          
          echo 'Hello world '
    

  - job: "Prod"
    pool: server
    dependsOn: "Deploy"
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'Mohan Azure'
        method: 'POST'
        body: |
          {
           "buildNumber": "$(build.buildId)",
           "isMultiBranch": "true",
           "branchName": "$(build.sourceBranchName)"
          }
        waitForCompletion: 'true'

    - task: Delay@1
      inputs:
        delayForMinutes: '0'
        

  
  




  



  